#!/usr/bin/env bash

##########################################################
# Created by: r0m5s
#
# Github: github.com/r0m5s
#
# Thank you for using this script :D 
# I hope it has good use to you
##########################################################

# Name of the Appimage file
filename=$(curl -s https://github.com/yuzu-emu/yuzu-mainline/releases | grep ".AppImage" | sed -n "1p" | cut -d\" -f2 | cut -d / -f7)

# If last version is installed exit code
[[ -e $HOME/.local/bin/$filename ]] && echo "Already up to date" && exit 1

# Remove previous version
rm -f $HOME/.local/bin/yuzu-*.AppImage

version=$(curl -s https://github.com/yuzu-emu/yuzu-mainline/releases | grep ".AppImage" | sed -n "1p" | cut -d\" -f2 | cut -d / -f6) # Version of the current mainline
package=$(echo https://github.com$(curl -s https://github.com/yuzu-emu/yuzu-mainline/releases | grep ".AppImage" | sed -n "1p" | cut -d\" -f2)) # Latest release download link

echo -e "
-------------------------------------------------------
Yuzu Mainline Appimage

Version: $version
-------------------------------------------------------
"
sleep 4

#Download the AppImage
echo "Downloading package"
wget -q --inet4-only --show-progress --directory-prefix=/tmp $package

[[ ! -f $HOME/.local/bin ]] && mkdir -p $HOME/.local/bin
install -m755 /tmp/$filename $HOME/.local/bin

# Create/Update desktop file
cat << EOF > yuzu.desktop
[Desktop Entry]
Name=Yuzu
Icon=$HOME/.local/share/icons/yuzu.svg
Exec=$HOME/.local/bin/$filename
Terminal=false
Type=Application
Categories=Game;Emulator;Qt;
StartupNotify=true
NoDisplay=false
EOF

[[ ! -f $HOME/.local/share/applications ]] && mkdir -p $HOME/.local/share/applications
install -m644 yuzu.desktop $HOME/.local/share/applications

# Yuzu image icon
[[ ! -f $HOME/.local/share/icons ]] && mkdir -p $HOME/.local/share/icons 
install -m644 yuzu.svg $HOME/.local/share/icons

# Clean installation files
rm /tmp/$filename

echo -e "\nLatest version installed"
